// apps/keymaster-docs/docs/.vitepress/components/MultipleShortcutsDemo.vue
<template>
  <div class="multiple-shortcuts-demo">
    <p class="multiple-shortcuts-demo__title">
      <strong v-if="isZh">多个快捷键组合演示</strong>
      <strong v-else>Multiple Shortcuts Demo</strong>
    </p>
    <p class="multiple-shortcuts-demo__description">
      <template v-if="isZh">
        在同一个组件中可以绑定多个不同的快捷键，每个快捷键都有独立的处理逻辑。
      </template>
      <template v-else>
        Multiple different shortcuts can be bound in the same component, each with independent
        handling logic.
      </template>
    </p>
    <div class="multiple-shortcuts-demo__shortcuts">
      <div class="multiple-shortcuts-demo__shortcut-item">
        <kbd>Ctrl</kbd>+<kbd>S</kbd>
        <span>{{ isZh ? '保存' : 'Save' }}</span>
      </div>
      <div class="multiple-shortcuts-demo__shortcut-item">
        <kbd>Ctrl</kbd>+<kbd>Z</kbd>
        <span>{{ isZh ? '撤销' : 'Undo' }}</span>
      </div>
      <div class="multiple-shortcuts-demo__shortcut-item">
        <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd>
        <span>{{ isZh ? '重做' : 'Redo' }}</span>
      </div>
      <div class="multiple-shortcuts-demo__shortcut-item">
        <kbd>Ctrl</kbd>+<kbd>B</kbd>
        <span>{{ isZh ? '加粗' : 'Bold' }}</span>
      </div>
      <div class="multiple-shortcuts-demo__shortcut-item">
        <kbd>Ctrl</kbd>+<kbd>I</kbd>
        <span>{{ isZh ? '斜体' : 'Italic' }}</span>
      </div>
      <div class="multiple-shortcuts-demo__shortcut-item">
        <kbd>Ctrl</kbd>+<kbd>K</kbd>
        <span>{{ isZh ? '插入链接' : 'Insert Link' }}</span>
      </div>
    </div>
    <p class="multiple-shortcuts-demo__status">
      <template v-if="isZh">最近触发：</template>
      <template v-else>Last triggered:</template>
      <strong>{{ lastAction || (isZh ? '暂无' : 'None') }}</strong>
    </p>
    <p v-if="message" class="multiple-shortcuts-demo__message">
      {{ message }}
    </p>
    <div class="multiple-shortcuts-demo__history">
      <p class="multiple-shortcuts-demo__history-title">
        {{ isZh ? '操作历史：' : 'Action History:' }}
      </p>
      <ul class="multiple-shortcuts-demo__history-list">
        <li v-for="(action, index) in history" :key="index">
          {{ action }}
        </li>
        <li v-if="history.length === 0" class="multiple-shortcuts-demo__history-empty">
          {{ isZh ? '暂无操作记录' : 'No action records' }}
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, computed } from 'vue';
import { useRoute } from 'vitepress';
import { registerKeyBinding } from '@keekuun/keymaster-react';

const route = useRoute();
const isZh = computed(() => route.path.startsWith('/zh/'));

const lastAction = ref('');
const message = ref('');
const history = ref<string[]>([]);
let timer: number | null = null;

const cleanups: Array<() => void> = [];

function showAction(text: string) {
  lastAction.value = text;
  message.value = text;
  history.value.unshift(text);
  if (history.value.length > 10) {
    history.value = history.value.slice(0, 10);
  }

  if (timer !== null) {
    window.clearTimeout(timer);
  }

  timer = window.setTimeout(() => {
    message.value = '';
  }, 2000);
}

onMounted(() => {
  // 注册多个快捷键
  cleanups.push(
    registerKeyBinding(
      'ctrl+s',
      () => {
        showAction(isZh.value ? '💾 保存' : '💾 Save');
      },
      { preventDefault: true },
    ),
  );

  cleanups.push(
    registerKeyBinding('ctrl+z', () => {
      showAction(isZh.value ? '↶ 撤销' : '↶ Undo');
    }),
  );

  cleanups.push(
    registerKeyBinding('ctrl+shift+z', () => {
      showAction(isZh.value ? '↷ 重做' : '↷ Redo');
    }),
  );

  cleanups.push(
    registerKeyBinding(
      'ctrl+b',
      () => {
        showAction(isZh.value ? '**加粗**' : '**Bold**');
      },
      { preventDefault: true },
    ),
  );

  cleanups.push(
    registerKeyBinding(
      'ctrl+i',
      () => {
        showAction(isZh.value ? '*斜体*' : '*Italic*');
      },
      { preventDefault: true },
    ),
  );

  cleanups.push(
    registerKeyBinding(
      'ctrl+k',
      () => {
        showAction(isZh.value ? '🔗 插入链接' : '🔗 Insert Link');
      },
      { preventDefault: true, stopPropagation: true },
    ),
  );
});

onBeforeUnmount(() => {
  cleanups.forEach((cleanup) => cleanup());
  if (timer !== null) window.clearTimeout(timer);
});
</script>

<style scoped>
.multiple-shortcuts-demo {
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  padding: 16px;
  margin: 16px 0;
  background-color: var(--vp-c-bg-soft);
  width: 100%;
  box-sizing: border-box;
  overflow-x: hidden;
}

.multiple-shortcuts-demo__title {
  margin: 0 0 8px;
  font-size: 16px;
}

.multiple-shortcuts-demo__description {
  margin: 0 0 12px;
  color: var(--vp-c-text-2);
  font-size: 14px;
}

.multiple-shortcuts-demo__shortcuts {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(max-content, 1fr));
  gap: 8px;
  margin-bottom: 12px;
  width: 100%;
  box-sizing: border-box;
}

.multiple-shortcuts-demo__shortcut-item {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 4px;
  background-color: var(--vp-c-bg);
  font-size: 14px;
  white-space: nowrap;
  box-sizing: border-box;
}

.multiple-shortcuts-demo__shortcut-item span {
  color: var(--vp-c-text-2);
  white-space: nowrap;
}

.multiple-shortcuts-demo__shortcut-item kbd {
  white-space: nowrap;
}

.multiple-shortcuts-demo__status {
  margin: 12px 0 4px;
  font-size: 14px;
}

.multiple-shortcuts-demo__message {
  margin: 4px 0 0;
  color: var(--vp-c-brand-1);
  font-weight: 500;
}

.multiple-shortcuts-demo__history {
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid var(--vp-c-divider);
}

.multiple-shortcuts-demo__history-title {
  margin: 0 0 8px;
  font-size: 14px;
  font-weight: 500;
}

.multiple-shortcuts-demo__history-list {
  margin: 0;
  padding-left: 20px;
  font-size: 13px;
  color: var(--vp-c-text-2);
  max-height: 120px;
  overflow-y: auto;
}

.multiple-shortcuts-demo__history-empty {
  color: var(--vp-c-text-3);
  font-style: italic;
}

kbd {
  display: inline-block;
  padding: 2px 6px;
  margin: 0 2px;
  border-radius: 4px;
  border: 1px solid var(--vp-c-divider);
  background-color: var(--vp-c-bg-alt);
  font-size: 12px;
}
</style>

// apps/keymaster-docs/docs/.vitepress/components/react/MultipleShortcutsDemo.tsx
import React, { useState, useEffect } from 'react';
import { registerKeyBinding } from '@keekuun/keymaster-react';
import './MultipleShortcutsDemo.css';

interface MultipleShortcutsDemoProps {
  isZh?: boolean;
}

export default function MultipleShortcutsDemo({ isZh = false }: MultipleShortcutsDemoProps) {
  const [lastAction, setLastAction] = useState('');
  const [message, setMessage] = useState('');
  const [history, setHistory] = useState<string[]>([]);
  const timerRef = React.useRef<number | null>(null);
  const cleanupsRef = React.useRef<Array<() => void>>([]);

  function showAction(text: string) {
    setLastAction(text);
    setMessage(text);
    setHistory((prev) => {
      const newHistory = [text, ...prev];
      return newHistory.slice(0, 10);
    });

    if (timerRef.current !== null) {
      window.clearTimeout(timerRef.current);
    }

    timerRef.current = window.setTimeout(() => {
      setMessage('');
      timerRef.current = null;
    }, 2000);
  }

  useEffect(() => {
    // 注册多个快捷键
    cleanupsRef.current.push(
      registerKeyBinding(
        'ctrl+s',
        () => {
          showAction(isZh ? '💾 保存' : '💾 Save');
        },
        { preventDefault: true },
      ),
    );

    cleanupsRef.current.push(
      registerKeyBinding('ctrl+z', () => {
        showAction(isZh ? '↶ 撤销' : '↶ Undo');
      }),
    );

    cleanupsRef.current.push(
      registerKeyBinding('ctrl+shift+z', () => {
        showAction(isZh ? '↷ 重做' : '↷ Redo');
      }),
    );

    cleanupsRef.current.push(
      registerKeyBinding(
        'ctrl+b',
        () => {
          showAction(isZh ? '**加粗**' : '**Bold**');
        },
        { preventDefault: true },
      ),
    );

    cleanupsRef.current.push(
      registerKeyBinding(
        'ctrl+i',
        () => {
          showAction(isZh ? '*斜体*' : '*Italic*');
        },
        { preventDefault: true },
      ),
    );

    cleanupsRef.current.push(
      registerKeyBinding(
        'ctrl+k',
        () => {
          showAction(isZh ? '🔗 插入链接' : '🔗 Insert Link');
        },
        { preventDefault: true, stopPropagation: true },
      ),
    );

    return () => {
      cleanupsRef.current.forEach((cleanup) => cleanup());
      cleanupsRef.current = [];
      if (timerRef.current !== null) {
        window.clearTimeout(timerRef.current);
      }
    };
  }, [isZh]);

  return (
    <div className="multiple-shortcuts-demo">
      <p className="multiple-shortcuts-demo__title">
        <strong>{isZh ? '多个快捷键组合演示' : 'Multiple Shortcuts Demo'}</strong>
      </p>
      <p className="multiple-shortcuts-demo__description">
        {isZh
          ? '在同一个组件中可以绑定多个不同的快捷键，每个快捷键都有独立的处理逻辑。'
          : 'Multiple different shortcuts can be bound in the same component, each with independent handling logic.'}
      </p>
      <div className="multiple-shortcuts-demo__shortcuts">
        <div className="multiple-shortcuts-demo__shortcut-item">
          <kbd>Ctrl</kbd>+<kbd>S</kbd>
          <span>{isZh ? '保存' : 'Save'}</span>
        </div>
        <div className="multiple-shortcuts-demo__shortcut-item">
          <kbd>Ctrl</kbd>+<kbd>Z</kbd>
          <span>{isZh ? '撤销' : 'Undo'}</span>
        </div>
        <div className="multiple-shortcuts-demo__shortcut-item">
          <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd>
          <span>{isZh ? '重做' : 'Redo'}</span>
        </div>
        <div className="multiple-shortcuts-demo__shortcut-item">
          <kbd>Ctrl</kbd>+<kbd>B</kbd>
          <span>{isZh ? '加粗' : 'Bold'}</span>
        </div>
        <div className="multiple-shortcuts-demo__shortcut-item">
          <kbd>Ctrl</kbd>+<kbd>I</kbd>
          <span>{isZh ? '斜体' : 'Italic'}</span>
        </div>
        <div className="multiple-shortcuts-demo__shortcut-item">
          <kbd>Ctrl</kbd>+<kbd>K</kbd>
          <span>{isZh ? '插入链接' : 'Insert Link'}</span>
        </div>
      </div>
      <p className="multiple-shortcuts-demo__status">
        {isZh ? '最近触发：' : 'Last triggered:'}{' '}
        <strong>{lastAction || (isZh ? '暂无' : 'None')}</strong>
      </p>
      {message && <p className="multiple-shortcuts-demo__message">{message}</p>}
      <div className="multiple-shortcuts-demo__history">
        <p className="multiple-shortcuts-demo__history-title">
          {isZh ? '操作历史：' : 'Action History:'}
        </p>
        <ul className="multiple-shortcuts-demo__history-list">
          {history.length === 0 ? (
            <li className="multiple-shortcuts-demo__history-empty">
              {isZh ? '暂无操作记录' : 'No action records'}
            </li>
          ) : (
            history.map((action, index) => <li key={index}>{action}</li>)
          )}
        </ul>
      </div>
    </div>
  );
}
